version: "3.2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 16-bullseye

    volumes:
      - ..:/workspace:cached
      - /data/vhtmp:/workspace/downloads
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../init-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
